// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2_XFiS7h4XNPDhLv82XitTN-xujhJug',
    appId: '1:1030184824169:web:124f952f70ca64155be1f8',
    messagingSenderId: '1030184824169',
    projectId: 'fitness-app-a60bd',
    authDomain: 'fitness-app-a60bd.firebaseapp.com',
    storageBucket: 'fitness-app-a60bd.appspot.com',
    measurementId: 'G-EH4M5D2DEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQjhKtCAv993xUn7LrnXGS0crD_0f1nM',
    appId: '1:1030184824169:android:e6e180c4634bb60e5be1f8',
    messagingSenderId: '1030184824169',
    projectId: 'fitness-app-a60bd',
    storageBucket: 'fitness-app-a60bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhljyI-PPbQflJe6Ye4aDXKcXdxVnmsEs',
    appId: '1:1030184824169:ios:3f6f73459adb9f5d5be1f8',
    messagingSenderId: '1030184824169',
    projectId: 'fitness-app-a60bd',
    storageBucket: 'fitness-app-a60bd.appspot.com',
    iosClientId: '1030184824169-jlntgtsjg7o7kmshv612ktm61fn9v8tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.spFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhljyI-PPbQflJe6Ye4aDXKcXdxVnmsEs',
    appId: '1:1030184824169:ios:3f6f73459adb9f5d5be1f8',
    messagingSenderId: '1030184824169',
    projectId: 'fitness-app-a60bd',
    storageBucket: 'fitness-app-a60bd.appspot.com',
    iosClientId: '1030184824169-jlntgtsjg7o7kmshv612ktm61fn9v8tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.spFitnessApp',
  );
}
